### ISSUE TITLE
Liquidating offers wrong amounts per vault

### ISSUE THREAD

**Issue by n4n0GH** [alchemix-finance/alchemix-v2-react#149]
When trying to liquidate debt, the selected vault will base the max amount on the actual debt even though the deposit is not matching that value. See screenshot below.

![Screenshot_2024-08-20_at_1 55 27_PM](https://github.com/user-attachments/assets/962a1332-f937-4245-baad-34c733e78005)

Users should never be able to liquidate more debt than their deposit can cover.

From Discord:

> t0rb1k | UTC+2 — Today at 2:11 PM
> yeah looks completely off
> the issue is we do debt->underlying->yeildBalance, so it's based on debt rn
> n4n0 | (UTC+2) — Today at 2:14 PM
> mh ic it needs to account for max deposit in the actual vault then too
> t0rb1k | UTC+2 — Today at 2:14 PM
> so this should be externalMax and balance should be based on vault.shares i suppose

**Comment by t0rbik** [comment]
#153
