### ISSUE TITLE
Add text information/guardrails to migration function

### ISSUE THREAD

**Issue by KeenanLukeOM** [alchemix-finance/alchemix-v2-react#215]
**Context:** Migration functionally trades into the respective token of the target vault before deposit, which in fringe cases can cause loss of funds. In my personal case, this was due to low liquidity on the target pool for migration, which fell within the bounds of the 10% emergency threshold. AFAIK, this threshold was adjusted to 3% as a result, but should be confirmed by Scrub before implementation.

https://discord.com/channels/738480789464940634/1283226390753317004/1289474708022235197

**Suggestion:** Input the following text below "target vault" and the token denomination window.

"Warning: Under certain circumstances, slippage of up to 3% may occur upon migration to another vault. Visit our [Discord](https://discord.com/invite/alchemix) for support."

**Pictured suggestion:**

![image](https://github.com/user-attachments/assets/5189c21a-fc60-4f24-953b-dd9a4722fc7e)

_Note: I just uppercased Discord instead of hyperlink for visualization purposes._

**Comment by t0rbik** [comment]
Completed in #230, merged to prod in #238
